### ISSUE TITLE
2022.09.20

### ISSUE THREAD

**Issue by moonheekim0118** [woowacourse-study/2022-Halloween-YouDontKnowJS#3]
오늘부터 미션 화이티잉..

**Comment by liswktjs** [comment]
- 명시적 바인딩
    - call(), apply() 를 통해서 객체를 첫번째 인자로 받아 함수 호출시 이 객체를 this로 세팅한다. this를 지정한 객체로 직접 바인딩 하므로 이를 명시적 바인딩이라고 한다.
    
    ```jsx
    function foo(){
    	console.log(this.a);
    }
    var obj = {
    	a: 2
    } 
    
    foo.call(obj); // 2 
    ```
    
    - 만약 바인딩시 객체가 아닌 원시값을 넣어주게 되면 원시 값에 대응하는 객체로 래핑된다.
        - 각각 new String(), new Boolean(), new Number()로 래핑되고 이 과정을 박싱이라고 한다.

- 하드 바인딩
    
    ```jsx
    fuction foo(){
    	console.log(this.a);
    }
    
    var obj = {
    	a:2 
    }
    
    var bar = function(){
    	foo.call(obj);
    }
    
    bar(); // 2
    setTimeout(bar, 100); // 2
    bar.call(window); // 2
    ```
    
    - 하드 바인딩 된  ‘bar’은 재정의된 this에는 의미가 없다
    - bar 내부에서 항상 obj를 바인딩 하여 foo를 실행하게 된다. 이런 바인딩은 명시적이고 강력해서 하드 바인딩이라고 한다.
- new 바인딩
    - 자바스크립트에서의 생성자
        - new 연산자가 있을때 호출되는 일반 함수에 불과
    - 자바스크립트에서의 new는 함수를 생성하는 호출이다
        - new를 통한 생성자 호출 과정
            - 새로운 객체가 만들어진다
            - 새로 생성된 객체의 Prototype이 연결된다
            - 새로 생성된 객체는 해당 함수로 호출시 this로 바인딩 된다
            - 이 함수가 자신의 또 다른 객체를 반환하지 않는 한 new와 함께 호출된 함수는 자동으로 새로 생성된 객체를 반환한다

### this 바인딩의 우선순위

- 하드 코딩 > new 연산자 바인딩 >  명시적 바인딩 > 암시적 바인딩 > 전역객체
    - new 연산자로는 오버로딩을 할 수 없다
- this의 확정 규칙
    - new 함수로 호출했는가?
        - 맞다면, 새로 생성된 객체가 this이다
    - call 과 apply로 함수를 호출, bind 하드 바인딩 내부에 숨겨진 형태로 호출되었는가?
        - 맞다면, 명시적으로 지정된 객체가 this이다
    - 함수를 콘텍스트(암시적 바인딩), 즉 객체를 소유 또는 포함하는 형태로 호출하는가?
        - 맞다면, 콘텍스트 객체가 this이다
        
        ```jsx
        var bar = obj1.foo(); 
        ```
        
    - 그 외의 경우에 this는 기본값 (엄격모드에서는 undefined 비엄격모드는 전역객체)로 바인딩 된다
    

### 바인딩 예외

- this 무시
    - call , apply, bind 메서드에 첫번째 인자로 null 또는 undefined를 넘기면 this바인딩이 무시되고 기본 바인딩 규칙이 적용된다
    - null값을 this에 바인딩 하려는 이유
        - apply()
            - func.apply(thisArg, [argsArray])
            - thisArgs에는 this로 바인딩 될 값
            - [argsArray]에는 func에 호출되어야 하는 인수를 지정하는 유사배열 객체
            
            ```jsx
            function foo(a,b) {
            	console.log("a:"+ a + "b:" + b );
            }
            
            foo.apply(null, [2,3]); // a: 2 , b: 3
            ```
            
        - apply()의 경우 함수 호출 시 다수의 인자를 배열 값으로 쭉 펼쳐 보내는 용도로 쓰인다
        - 그래서 this에 어떤 값이 바인딩 되도 상관이 없는 경우 null을 인자로 넣는 경우가 있다
            - 하지만 이럴 때에 this에 null을 바이딩하는 것 보다 내용이 하나도 없으면서 전혀 위임되지 않은 객체가 필요하다
            - object.prototype으로 위임되지 않은 더 텅 빈 객체를 Object.create(null)를 활용해 만들 수 있다
            
- 소프트 바인딩
    
    ```jsx
    if(!Function.prototype.softBind){
    	Function.prototype.softBind = function(obj){
    		var fn = this;
    		var curried = [].slice.call(arguments, 1);
    		var bound = function() {
    			return fn.apply(
    				(!this || this === (window || global)) ? obj : this,
    						curried.concate.apply(curried, arguments)
    			);
    		};
    		bound.prototype = Object.create(fn.prototype);
    		return bound;
    		};
    };
    ```
    
    - this가 없거나, window global 같은 전역 객체일 경우 미리 준비한 기본 객체로 세팅한다 .

### 어휘적 this

- 화살표 함수
    - Enclosing Scope를 보고 this를 알아서 바인딩한다

**Comment by soyi47** [comment]
## 객체의 정의

- 객체를 정의하는 방법에는 1. 리터럴 형식과 2. 생성자 형식이 있다.
- 두 방식 모두 결과적으로 생성되는 객체는 같다. 둘의 유일한 차이는 리터럴 형식은 한 번의 선언으로 다수의 키/값 쌍을 프로퍼티로 추가할 수 있다는 점이다. 생성자 형식은 한 번에 한 프로퍼티만 추가할 수 있다.

```jsx
// 리터럴 형식
var myObj = {
	key: value
	// ...
}

// 생성자 형식
var myObj = new Object();
myObj.key = value;
```

- 자바스크립트의 함수는 일급 객체다. 즉 다른 함수에 인자로 전달할 수 있고, 다른 함수로부터 함수를 반환받을 수 있으며, 함수 자체를 변수에 할당하거나 자료 구조에 지정할 수도 있다.
- 자바스크립트의 함수는 기본적으로 객체이므로 일급이며 일반 객체와 똑같이 취급된다. 배열 역시 추가 기능이 구현된 객체의 일종이다.

## primitive literal은 어떻게 메서드를 사용할 수 있을까?

내장 객체라고 불리는 객체의 하위 타입들은 원시 타입과 연관되어 보이지만, 실제로는 내장 함수일 뿐이며 생성자로 사용되어 새 객체를 생성한다.

- 내장 객체에는 String, Number, Boolean, Object, Function, Array, Date, RegExp, Error
- “나는 문자열이야!”라는 원시 값은 객체가 아닌 primitive literal이며 immutable value다. 그러면 어떻게 우리는 내장 메서드를 사용할 수 있을까? 원시 값에 대해 프로퍼티/메서드를 호출하면 자바스크립트 엔진은 자동으로 내장 객체로 감싸져 강제 변환하여 메서드 접근이 가능하도록 한다. 여러 자바스크립트 커뮤니티에서는 되도록 생성자 형식을 지양하고 리터럴 형식을 사용하라고 적극 권장한다.

## 객체의 프로퍼티

- 객체에 프로퍼티를 저장하는 방식은 ECMAScript를 구현한 엔진 별로 조금씩 달라지는데, 일반적으로는 객체 컨테이너 그 자체에 담지 않는다. **객체 컨테이너에는 프로퍼티 값을 참조하는 프로퍼티 명이 담겨있다.**
- 객체에는 값을 가리키는 레퍼런스임에 주의하자. 그래서 객체의 복사는 얕은 복사와 깊은 복사로 나뉜다. 사본 객체가 원본 객체의 프로퍼티와 같은 대상을 가리키는 프로퍼티를 가지도록 복사된다면 이는 얕은 복사다. 다르게 프로퍼티가 가리키는 대상까지 모조리 복사하는 방식을 깊은 복사라고 한다.
- 객체에서 프로퍼티의 값에 접근하려면 ‘.’ 연산자, 또는 ‘[]’ 연산자를 사용한다. 일반적으로 ‘.a’ 구문을 프로퍼티 접근, ‘[”a”]’ 구문을 키 접근이라고 한다. 객체 프로퍼티 명은 언제나 문자열이다.
- **ES6**에는 **Computed Property Name**이라는 기능이 추가됐는데, 객체 리터럴 선언 구문의 키 이름 부분에 해당 표현식을 넣고 대괄호 []로 감싸면 된다.
    
    ```jsx
    var prefix = "foo";
    
    var myObject = {
    	[prefix + "bar"]: "hello",
    	[prefix + "baz"]: "world"
    }
    
    myObject["foobar"];  // hello
    myObject["foobaz"];  // world
    ```
    

- Symbol??
    
    값으로 익명의 객체 속성(object property)을 만들 수 있는 특성을 가진 원시 데이터 형식(primitive data type)
    

- ES5부터 모든 프로퍼티는 프로퍼티 서술자를 조회할 수 있다.
    
    ```jsx
    var myObject = {
    	a: 2
    };
    
    Object.getOwnPropertyDescriptor(myObject, "a");
    // { 
    // value: 2, 
    // writable: true, 
    // enumerable: true, 
    // configurable: true
    // }
    ```
    
    - writable
        - 프로퍼티 값의 쓰기 가능 여부
        - 쓰기 금지된 값을 수정하려고 하면 비엄격 모드에서는 조용히 실패한다. 엄격 모드에서는 TypeError가 발생한다.
    - configurable
        - `defineProperty()`를 통한 프로퍼티의 서술자 설정 가능 여부
        - 프로퍼티 서술자 변경이 불가능한데 `defineProperty()`를 호출하면 TypeError가 발생한다.
        - `delete` 연산자로 존재하는 프로퍼티 삭제도 금지된다.
    - enumerable
        - 열거 가능 여부, 객체 프로퍼티를 열거하는 구문(for … in)에서 해당 프로퍼티의 표출 여부
        - 보통 사용자 정의 프로퍼티는 true가 기본값이라 열거할 수 있다. 감추고 싶은 프로퍼티에 한하여 false로 세팅하자.

**Comment by prefer2** [comment]
# 타입

# 내장 타입

null, undefined, boolean, number, string, object, symbol

object를 제외한 타입을 원시 타입(primitive type)이라고 한다

값 타입은 typeof 연산자로 알 수 있다. 

```jsx
typeof null === 'object' // true
```

nulld은 falsy한 유일한 원시 값이지만 타입은 object인 특별한 존재이다

```jsx
typeof function a() {} === 'function'
```

typeof 반환값을 보면 function이 내장 타입처럼 보이지만 실제로는 object의 하위 타입이다. 함수는 호출 가능한 객체(내부 프로퍼티 [[Call]]로 호출 할 수 있는 객체)이다. 함수는 객체라서 함수에 프로퍼티를 둘 수 있다.

## 값은 타입을 가진다

값에는 타입이 있지만, 변수에는 타입이 없다. 자바스크립트는 타입 강제를 하지 않는다.

typeof는 실제로는 이 변수에 들어있는 값의 타입은 무엇이니?라고 묻는 것이다.

값이 없는 변수의 값은 undefined다. `undefined`는 접근 가능한 스코프에 변수가 선언되었으나 현재 아무런 값도 할당되지 않은 상태를 말한다.

```jsx
typeof b; // undefined
```

선언되지 않은 변수도 typeof를 하면 undefined로 나온다. 브라우저는 따로 오류처리를 하지 않는다.

```jsx
var a = [];
a[0] = 1;
a[2] = [3];

a[1]; // undefined. a[1] = undefined로 세팅한 것도 똑같지는 않다.
a.length; //3
```

자바스크립트의 배열은 어떤 타입의 값이라도 담을 수 있는 그릇이다. 배열의 크기는 미리 정하지 않고도 선언할 수 잇으며 원하는 값을 추가하면 된다.

# 값

# 배열

자바스크립트의 배열은 어떤 타입의 값이라도 담을 수 있는 그릇이다. 배열의 크기는 미리 정하지 않고도 선언할 수 잇으며 원하는 값을 추가하면 된다.

```jsx
var a = [ 1, '2', [3]];
```

구멍 난 배열을 다룰 때는 조심해야 한다. 실행은 되지만 혼란스러울 수 있다.

```jsx
var a = [];
a[0] = 1;
a[2] = [3];

a[1]; // undefined. a[1] = undefined로 세팅한 것도 똑같지는 않다.
a.length; //3
```

배열의 키 프로퍼티 문자열을 추가할 수 있다. 하지만 배열 length가 증가하지는 않는다. 문자열 값이 10진수 숫자이면 마치 숫자키를 사용한 것과 같은 결과가 나온다. 일반적으로 배열에 문자열 타입의 키를 두지 말자.

```jsx
var a = [];
a[0] = 1;
a['foo'] = 2;
a.length; // 1
a['foo']; // 2

a['13'] = 42;
a.length; //14
```

### 유사 배열

DOM, arguments등은 유사배열 형태이다. `Array.from()`으로 배열 형태로 전환할 수 있다.

# 문자열

자바스크립트 문자열을 문자 배열과 동일하지 않다. 문자열은 유사 배열이다. length, indexOf(), concat() 메서드를 가진다.

문자열은 불변값이지만 배열은 가변값이다. 문자열은 불변값이므로 내용을 바로 변경하지 않고 항상 새로운 문자열을 생성한 후 반환한다. 

문자열 자체에 작업을 빈번하게 수행하는 경우라면 문자 단위로 저장하는 배열로 취급하는 것이 나을 수 있다. 문자열로 나타내야 할 때는 배열에 `join(’ ‘)`메서드를 호출하면 된다.

# 숫자

자바스크립트 숫자 타입은 number가 유일하며 정수, 부동 소수점 숫자를 모두 아우른다. 

아주 크거나 작은 숫자는 지수형으로 표시하며, toExponential() 메서드의 결과값과 같다.

숫자 값은 Number 객체 래퍼로 boxing할 수 있기 때문에 Number.prototype 메서드로 접근할 수 있다.

### 작은 소수 값

```jsx
0.1 + 0.2 === 0.3 // false
```

0.1 과 0.2는 정확하게 그 숫자가 아니다. 미세한 반올림 오차는 Numer.EPSILON으로 비교할 수 있다. 

### 정수인지 확인

Number.isInteger()로 어떤 값의 정수 여부를 확인한다.

# 특수 값

null은 식별자가 아닌 특별한 키워드라 뭔가 할당할 수는 없다.

## undefined

void는 어떤 값이든 무효로 만들어, 항상 결과값을 undefined로 만든다. void 0, undefind는 모두 같다. void 연산자는 어떤 표현식의 결과값이 없다는 것을 확실히 밝혀야 할 때 요긴하다. void는 값이 존재하는 곳에서 그 값이 undefined가 되어야 하는 경우에만 사용하자.

## 특수 숫자

### NAN

숫자가 아님. 수학 연산 시 두 피연산자가 전부 숫자가 아닌 경우 유효한 숫자가 나올 수 없어 결과가 NaN이다. NaN은 비교가 불가능하다

```jsx
let a = 2 / 'foo' // NaN
typeof a === 'number' // true

a == NaN // false
a === NaN // false
NaN === NaN // false

```

NaN여부는 `Number.isNaN()`으로 확인한다.

### 무한대

```jsx
let a = 1 / 0 // Infinity
let b = -1 / 0 // -Infinity
```

### 특이한 동등 비교

`Object.is()`로 두 값이 절대적으로 동등한지 확인할 수 있다. ==나 ===로 충분히 답을 얻을 수 있다면 [Object.is](http://object.is/)()는 사용하지 않는 것이 좋다. 특히한 동등 비교에서 주로 쓴다.
